### PR TITLE
checking donator key format when using >redeemkey

### LINKED ISSUE #530: Miki does not respond when a donator key is invalid
Miki does not respond when a donator key is invalid

1. >redeemkey [code]
2. usually miki responds with "something went wrong, this key is invalid!"

**Expected behavior**
 miki should respond with an error message similar to  "something went wrong, this key is invalid!"

**Screenshots**
 how it should work:
image
 current behavior:
image

### PR DESCRIPTION
**Pull request by Xetera**
image

fixes #530

### CODE REVIEW

File: src/Miki/Modules/Donator/DonatorModule.cs [hunk 1]
```diff
@@ -16,6 +16,8 @@
 using Miki.Framework.Commands.Attributes;
 using Miki.Framework.Commands;
 using Miki.Framework.Commands.Nodes;
+using Miki.Localization.Exceptions;
+using Miki.Modules.Exceptions;
```
Comment (velddev) [inline src/Miki/Modules/Donator/DonatorModule.cs]: Change this to Miki.Modules.Donators.Exceptions

File: src/Miki/Modules/Donator/Exceptions/InvalidKeyFormatException.cs [hunk 2]
```diff
@@ -0,0 +1,14 @@
+using Miki.Localization;
+using Miki.Localization.Exceptions;
+
+namespace Miki.Modules.Exceptions
```
Comment (velddev) [inline src/Miki/Modules/Donator/Exceptions/InvalidKeyFormatException.cs]: Should be `Miki.Modules.Donator.Exceptions`

File: src/Miki/Modules/Donator/DonatorModule.cs [hunk 3]
```diff
@@ -16,6 +16,8 @@
...
 
 namespace Miki.Modules
```
Comment (velddev) [inline src/Miki/Modules/Donator/DonatorModule.cs]: Turn to Miki.Modules.Donator

**Review by velddev — CHANGES_REQUESTED** [review]
