### PR TITLE
Fix Loved & Hated pastas

### LINKED ISSUE #318: >hatedpasta/>lovedpasta <@mention> embed title is wrong.
When using the command as a mention, the embed's title is the user executing the command's name, not the user being mentioned. Just to be clear, the content is correct, just the title is wrong.

### PR DESCRIPTION
**Pull request by Pao-Lumu**
Add a decrement to page number when applicable.
Add check for page being less than zero; if True, set it to the first page.
Change Math.Ceiling() to Math.Floor() in maxPage definition to forgo the `maxPage - 1` when using it.
Change hatedpastas/lovedpastas embed reference from `e.Author` to `targetUser`
Remove weird double comparison in an if statement I committed like 3 months ago.

Fixes #318 & #331

### CODE REVIEW

File: Miki/Modules/PastaModule.cs [hunk 1]
```diff
@@ -72,7 +72,7 @@ public class PastaModule
             if (!string.IsNullOrWhiteSpace(e.arguments))
             {
                 List<string> arguments = e.arguments.Split(' ').ToList();
-                if (int.TryParse(arguments[0], out page) || int.TryParse(arguments[0], out page))
```
Comment (velddev) [inline Miki/Modules/PastaModule.cs:75]: How drunk was I when i wrote this?

**Review by velddev — APPROVED** [review]
